language: objective-c
osx_image: xcode11

addons:
  homebrew:
    packages:
    - carthage
    update: true

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

addons:
  ssh_known_hosts: github.com

notifications:
  email: false

before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build as dynamic frameworks
  - carthage update --configuration DEBUG
  - xcodebuild build clean -project SDWebImageSVGKitPlugin.xcodeproj -scheme 'SDWebImageSVGKitPlugin iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
  - xcodebuild build clean -project SDWebImageSVGKitPlugin.xcodeproj -scheme 'SDWebImageSVGKitPlugin tvOS' -sdk appletvsimulator -configuration Debug | xcpretty -c
  - xcodebuild build clean -project SDWebImageSVGKitPlugin.xcodeproj -scheme 'SDWebImageSVGKitPlugin macOS' -sdk macosx -configuration Debug | xcpretty -c

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/SDWebImageSVGKitPlugin.xcworkspace -scheme 'SDWebImageSVGKitPlugin-Example' -sdk iphonesimulator -destination 'name=iPhone 8' -configuration Debug | xcpretty -c
  - xcodebuild build -workspace Example/SDWebImageSVGKitPlugin.xcworkspace -scheme 'SDWebImageSVGKitPlugin-Example macOS' -sdk macosx -configuration Debug | xcpretty -c
